Traceback (most recent call last):
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\ryanjoung\.conda\envs\mybook\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Train and Test
cm, cr = train_and_test(model_name, x_train, x_test, y_train, y_test)
print('\n-----Confusion Matrix-----\n')
print(cm)
print('\n-----Classification Report-----\n')
print(cr)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
[1;32mC:\Users\RYANJO~1\AppData\Local\Temp/ipykernel_32668/2709227883.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# Train and Test[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mcm[0m[1;33m,[0m [0mcr[0m [1;33m=[0m [0mtrain_and_test[0m[1;33m([0m[0mmodel_name[0m[1;33m,[0m [0mx_train[0m[1;33m,[0m [0mx_test[0m[1;33m,[0m [0my_train[0m[1;33m,[0m [0my_test[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mprint[0m[1;33m([0m[1;34m'\n-----Confusion Matrix-----\n'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mprint[0m[1;33m([0m[0mcm[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mprint[0m[1;33m([0m[1;34m'\n-----Classification Report-----\n'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Users\RYANJO~1\AppData\Local\Temp/ipykernel_32668/932345000.py[0m in [0;36mtrain_and_test[1;34m(model_name, x_train, x_test, y_train, y_test)[0m
[0;32m      6[0m     [1;31m# train and test[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      7[0m     [0mmodel[0m [1;33m=[0m [0mMultinomialNB[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 8[1;33m     [0mmodel[0m[1;33m.[0m[0mfit[0m[1;33m([0m[0mx_train[0m[1;33m,[0m [0my_train[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      9[0m     [0my_pred[0m [1;33m=[0m [0mmodel[0m[1;33m.[0m[0mpredict[0m[1;33m([0m[0mx_test[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     10[0m [1;33m[0m[0m

[1;32m~\.conda\envs\mybook\lib\site-packages\sklearn\naive_bayes.py[0m in [0;36mfit[1;34m(self, X, y, sample_weight)[0m
[0;32m    636[0m [1;33m[0m[0m
[0;32m    637[0m         [0mself[0m[1;33m.[0m[0m_init_counters[0m[1;33m([0m[0mn_effective_classes[0m[1;33m,[0m [0mn_features[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 638[1;33m         [0mself[0m[1;33m.[0m[0m_count[0m[1;33m([0m[0mX[0m[1;33m,[0m [0mY[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    639[0m         [0malpha[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_check_alpha[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    640[0m         [0mself[0m[1;33m.[0m[0m_update_feature_log_prob[0m[1;33m([0m[0malpha[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\.conda\envs\mybook\lib\site-packages\sklearn\naive_bayes.py[0m in [0;36m_count[1;34m(self, X, Y)[0m
[0;32m    769[0m     [1;32mdef[0m [0m_count[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mX[0m[1;33m,[0m [0mY[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    770[0m         [1;34m"""Count and smooth feature occurrences."""[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 771[1;33m         [0mcheck_non_negative[0m[1;33m([0m[0mX[0m[1;33m,[0m [1;34m"MultinomialNB (input X)"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    772[0m         [0mself[0m[1;33m.[0m[0mfeature_count_[0m [1;33m+=[0m [0msafe_sparse_dot[0m[1;33m([0m[0mY[0m[1;33m.[0m[0mT[0m[1;33m,[0m [0mX[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    773[0m         [0mself[0m[1;33m.[0m[0mclass_count_[0m [1;33m+=[0m [0mY[0m[1;33m.[0m[0msum[0m[1;33m([0m[0maxis[0m[1;33m=[0m[1;36m0[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\.conda\envs\mybook\lib\site-packages\sklearn\utils\validation.py[0m in [0;36mcheck_non_negative[1;34m(X, whom)[0m
[0;32m   1066[0m [1;33m[0m[0m
[0;32m   1067[0m     [1;32mif[0m [0mX_min[0m [1;33m<[0m [1;36m0[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1068[1;33m         [1;32mraise[0m [0mValueError[0m[1;33m([0m[1;34m"Negative values in data passed to %s"[0m [1;33m%[0m [0mwhom[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1069[0m [1;33m[0m[0m
[0;32m   1070[0m [1;33m[0m[0m

[1;31mValueError[0m: Negative values in data passed to MultinomialNB (input X)
ValueError: Negative values in data passed to MultinomialNB (input X)

